### ISSUE TITLE
Adding image to each recipe

### ISSUE THREAD

**Issue by sydneychirls29** [IntroToCode/Spring22_Recipes_Codemates6#27]
## 💬 Discussion topic

Should we add an image to each recipe?

## ❗ Potential issues

After adding images, we should confirm that they load correctly when looking at the code for each recipe.

## 👥 People to consult

Whoever doesn't have a PR for each recipe might want to take this (if all other sections are complete).

@asborov @kat-law @eliasspringer @thisisvc @mdubshere @Nikiness 

## Acceptance criteria

Each recipe has an image attached.

**Comment by asborov** [comment]
I think we should add images to the recipes if people still need to contribute to the recipe and don't know what else to add.

**Comment by Nikiness** [comment]
I added images to each recipe!

**Comment by sydneychirls29** [comment]
Hi @Nikiness! I think we are supposed to open pull requests that have to be reviewed by 2 other members of the team before merging / adding anything to our recipes! 

Also it looks like the images are just links?

<img width="1135" alt="Screen Shot 2022-04-07 at 10 51 57 AM" src="https://user-images.githubusercontent.com/101293719/162266116-a6c7041b-fce0-4447-9946-12ce1f6dfdb7.png">

**Comment by Nikiness** [comment]
whoops should work now lol thanks for letting me know

**Comment by sydneychirls29** [comment]
Closing out this issue now that we have images on each recipe! Thanks @Nikiness for adding 💯

**Comment by mdubshere** [comment]
Ooh I love that idea! People will flock to our website due to its sumptuous
images of decadent recipes!
