### ISSUE TITLE
Breakfast Breakdown

### ISSUE THREAD

**Issue by sydneychirls29** [IntroToCode/Spring22_Recipes_Codemates6#4]
Katherine to start Omelette breakfast recipe!

**Comment by asborov** [comment]
I am going to add some ingredients to the breakfast recipe. Who is going to write the recipe steps?

**Comment by kat-law** [comment]
no one has wrote detailed steps yet, you can go ahead!

**Comment by sydneychirls29** [comment]
Closing this issue because we have made progress on the breakfast recipe and this issue has been taken over by issue #8.
